name:Github Action No. 2

on:
  push:
    branches:["main"]

jobs:
  build:
    runs-on:ubuntu-latest
     steps:
      -name:checkout
        uses:action/checkout@v3  
      -name:Setup Node
        uses:actions/setup-node@v3
        with:
          node-version:"16"
      -name:install dependencies
       run:npm ci
      -name:build project
       run:npm run deploy